
document.getElementById('firstname').value = sessionStorage.getItem("FirstName")
document.getElementById('othernames').value = sessionStorage.getItem("OtherNames")
document.getElementById('maidensurname').value = sessionStorage.getItem("MaidenSurname")
document.getElementById('gender').value = sessionStorage.getItem("Gender")
document.getElementById('dobtext').value = sessionStorage.getItem("DateOfBirth")
document.getElementById('pob').value = sessionStorage.getItem("PlaceOfBirth")
document.getElementById('status').value = sessionStorage.getItem("Status")
document.getElementById('birthorder').value = sessionStorage.getItem("BirthOrder")
document.getElementById('mother').value = sessionStorage.getItem("MotherID")
document.getElementById('father').value = sessionStorage.getItem("FatherID")
document.getElementById('spouse').value = sessionStorage.getItem("SpouseID")
document.getElementById('domtext').value = sessionStorage.getItem("DateOfMarriage")
document.getElementById('pom').value = sessionStorage.getItem("PlaceOfMarriage")
document.getElementById('childrencount').value = sessionStorage.getItem("ChildrenCount")
document.getElementById('siblingscount').value = sessionStorage.getItem("SiblingsCount")
document.getElementById('contactperson').value = sessionStorage.getItem("ContactPerson")
document.getElementById('contactdetails').value = sessionStorage.getItem("ContactDetails")